name: Documentation Update

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material==9.1 mkdocstrings==0.22
        pip install mkdocs
        
    - name: Generate Documentation
      run: |
        mkdocs build -d webpage --clean
        cp -r webpage/* site/
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: site/
        retention-days: 1
        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    needs: ['build']
    steps:
      - name: Pages deploy
        id: deployment
        uses: actions/deploy-pages@v2.0.3
        with:
          token: ${{ github.token }}